#!/usr/bin/env zsh
cd $ZDOTDIR || exit 1

typeset -A files=(init .zshrc env .zshenv profile .zprofile)

clean () {
    rm -fv .*.zwc(N) ${~${(k)files}/%/'/**/*.bundle(N)'} >&2 2>/dev/null
}

compile () {
    awk_program='
    !/^\s*(#|$)/ {
        if (FILENAME ~ /\.zshx$/) {
            system(FILENAME);
            nextfile;
        }
        print;
    }'

    for dir file in ${(kv)files}; do
        chmod +x $dir/**/*.zshx(Nr^x) 2>/dev/null
        awk $awk_program $dir/**/*.(zsh|zshx|bundle)(Nr) > $file
        zcompile -UR $file
        print -u2 "Created: $file"
    done
}

update () {
    antibody update >&2
    for script in ${~${(k)files}/%/'/**/update-script(Nr)'}; do
        print -u2 "Sourcing: $script"
        source $script
    done
}

print_help () {
    help_message='Subcommands: clean compile update'
    echo $help_message
}

(( $# )) || print_help
for command; do
    case $command in
    clean)   clean      ;;
    compile) compile    ;;
    update)  update     ;;
    *)       print_help ;;
    esac
done
