# LunarVim

export LUNARVIM_RUNTIME_DIR="$XDG_DATA_HOME/lvim"
export LUNARVIM_CONFIG_DIR="$XDG_CONFIG_HOME/lvim"
export LUNARVIM_CACHE_DIR="$XDG_CACHE_HOME/lvim"
export LUNARVIM_BASE_DIR="$XDG_USER_OPT/lunarvim"
